### ISSUE TITLE
Set Up CI/CD Pipeline with GitHub Actions

### ISSUE THREAD

**Issue by shami544** [slem050/github-issue-manager-react#2]
### Set Up CI/CD Pipeline with GitHub Actions

**Description:**

We need to establish a continuous integration and deployment (CI/CD) pipeline using GitHub Actions. This will involve setting up a GitHub Actions runner, configuring linting, adding tests, and automating various checks to ensure code quality and reliability.

**Tasks:**

1. **GitHub Actions Setup:**
   - Create a `.github/workflows` directory in the repository.
   - Set up a basic GitHub Actions workflow for both the frontend and backend. This should include:
     - Building the React app and Node.js backend.
     - Running lint checks.
     - Running tests.

2. **Linting Configuration:**
   - Add a linting configuration file for both the frontend and backend.
     - For the frontend: Configure ESLint for React.
     - For the backend: Configure ESLint for Node.js.
   - Ensure linting is included in the GitHub Actions workflow.

3. **Testing Configuration:**
   - Add a testing framework for both the frontend and backend.
     - For the frontend: Set up Jest or a similar testing framework.
     - For the backend: Set up Mocha, Chai, or a similar testing framework.
   - Ensure tests are included in the GitHub Actions workflow.

4. **Additional CI/CD Configurations:**
   - Configure the workflow to run on pushes and pull requests to specific branches.
   - Set up caching for dependencies to speed up the build process.
   - Include steps for deploying the application if needed (e.g., to a staging environment).

5. **Documentation:**
   - Update the README.md file with instructions on how to work with GitHub Actions and the CI/CD pipeline.

**Acceptance Criteria:**

- GitHub Actions workflows are set up for both frontend and backend.
- Linting and testing configurations are added and integrated into the workflows.
- The pipeline runs automatically on push and pull requests.
- README.md is updated with relevant CI/CD instructions.

**Additional Notes:**

- Ensure that the workflows are tested and functioning correctly.
- Verify that linting and tests are properly configured and run as expected.

**Labels:** `enhancement`, `ci-cd`, `linting`, `testing`, `good first issue`

**Assignees:** [Optional: Assign to yourself or a team member]

**Comment by slem050** [comment]
done
